
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown
kramdown:
  input: GFM
  line_width: 80
  syntax_highlighter_opts:
    css_class: ''

sass:
  style: compressed

author: Adriane Justine Tan
email: eidoriantan@gmail.com
repository: eidoriantan/mp3tag.js

tagline: MP3 tagging library written in pure JavaScript
google_site_verification: pygHTY6j2sle4JJ1YmSCYlf8nxIxnq4u9bHe48Mc9do

logo: "/assets/images/logo.png"
color: "#2b594c"

navlinks:
  - name: Home
    directories:
      - "/"
      - "/index.html"

  - name: Documentations
    directories:
      - "/docs/"
      - "/docs/frames.html"
      - "/docs/index.html"
      - "/docs/mp3tag.html"
      - "/docs/usage.html"

  - name: Downloads
    directories:
      - "/downloads/"
      - "/downloads/index.html"

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap
